from setuptools import setup, find_packages

setup(
    name="Butler",
    version="1.0.0",
    description="A Python-based intelligent voice assistant.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="PAYDAY3",
    author_email="error123456ew@outlook.com",
    url="https://github.com/PAYDAY3/Butler",
    packages=find_packages(),
    install_requires=[
        "pyttsx3",
        "pydub",
        "playsound",
        "tempfile",
        "pyaud",
        "shutil",
        "prompt_toolkit",
        "pillow",
        "pygame",
        "watchdog",
        "dateutil",
        "sounddevice",
        "openpyxl",
        "docx",
        "PyPDF2",
        "requests>=2.32.0",
        "beautifulsoup4",
        "redis",
        "scrapy",
        "imaplib",
        "paramiko",
        "dotenv",
        "PIL",
        "nltk",
        "Crypto",
        "schedule",
        "twisted>=24.7.0rc1",
        "azure-cognitiveservices-speech"
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires='>=3.6',
    license="MIT",
    keywords="voice assistant, AI, Python",
    project_urls={
        "Documentation": "https://github.com/PAYDAY3/Butler/wiki",
        "Source": "https://github.com/PAYDAY3/Butler",
        "Tracker": "https://github.com/PAYDAY3/Butler/issues",
    },
    entry_points={
        'console_scripts': [
            'butler=jarvis:main',
        ],
    },
)
